#!/usr/bin/python
import os, prettytable

from keystoneclient.v2_0 import client as ks_client
from novaclient.v1_1 import client as nova_client

keystone = ks_client.Client(username=os.environ['OS_USERNAME'], password=os.environ['OS_PASSWORD'], 
                         tenant_name=os.environ['OS_TENANT_NAME'], auth_url=os.environ['OS_AUTH_URL'])
nova = nova_client.Client(username=os.environ['OS_USERNAME'], api_key=os.environ['OS_PASSWORD'], 
                         project_id=os.environ['OS_TENANT_NAME'], auth_url=os.environ['OS_AUTH_URL'],
                         service_type='compute')

tenant_dict = {}
for tenant in keystone.tenants.list():
    tenant_dict[tenant.id] = tenant.name

flavor_dict = {}
for flavor in nova.flavors.list():
    flavor_dict[flavor.id] = flavor.name

image_dict = {}
for image in nova.images.list():
    image_dict[image.id] = image.name

pt = prettytable.PrettyTable(["Tenant", "Status", "Flavor", "Name", "Image", "Created"])
servers = nova.servers.list(search_opts={'all_tenants': True})
for server in servers:
    pt.add_row([tenant_dict[server.tenant_id], server.status, flavor_dict[server.flavor.get("id")], 
        server.name, image_dict[server.image['id']], server._info["created"]])
print pt.get_string(sortby="Tenant")
